# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Tags: /tags
  Categories: /categories
  Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: YYYY-MM-DD

# Comments.
comments:
  # Disqus comments
  disqus_shortname: dark-lambda
  disqus_lang: ja

# Google Analytics Tracking ID
google_analytics: UA-37773191-3

# Social Accounts
twitter_url: https://twitter.com/LambdaDark
facebook_url: 
instagram_url: 
dribble_url: 
github_url: https://github.com/dark-lambda/dark-lambda.com
googleplus_url: 
behance_url: 
fivehundredpx_url: 
email_url: dev@dark-lambda.com
gitbook_url: https://book.dark-lambda.com/
rss_url: /atom.xml

# Footer About Text
footer_about: "dark-lambda は CTF コンテストへ参加する組織です。"

# Footer Copyright Line
footer_copyright: "@dark-lambda. All right reserved | Design & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"

algolia:
  applicationID: 721SZTS1FL
  apiKey: 1702779d1ab6d39d7e1f5794364ea7f9
  indexName: prod_dark-lambda.com